
import React, { useState } from 'react';
import { MOCK_REPORTS } from '../constants';
import { analyzeStock } from '../geminiService';

const Reports: React.FC = () => {
  const [selectedReportId, setSelectedReportId] = useState(MOCK_REPORTS[0].id);
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<any>(null);

  const activeReport = MOCK_REPORTS.find(r => r.id === selectedReportId) || MOCK_REPORTS[0];

  const handleAskGemini = async () => {
    setIsGenerating(true);
    const result = await analyzeStock(activeReport.symbol, activeReport.title);
    setAiAnalysis(result);
    setIsGenerating(false);
  };

  return (
    <div className="flex h-[calc(100vh-8rem)] -m-4 md:-m-8">
      <aside className="w-80 lg:w-96 flex flex-col border-r border-border-light bg-white flex-none overflow-hidden">
        <div className="p-5 border-b border-border-lighter">
          <h1 className="text-text-main text-xl font-bold tracking-tight mb-4">Saved Reports</h1>
          <div className="relative">
            <span className="material-symbols-outlined absolute left-3 top-2.5 text-text-placeholder text-[20px]">filter_list</span>
            <input 
              className="w-full pl-10 pr-4 py-2 bg-surface-accent border border-border-light rounded-lg text-sm focus:ring-1 focus:ring-primary" 
              placeholder="Filter by symbol..." 
            />
          </div>
        </div>
        <div className="flex-1 overflow-y-auto p-2 space-y-1">
          {MOCK_REPORTS.map(report => (
            <button
              key={report.id}
              onClick={() => { setSelectedReportId(report.id); setAiAnalysis(null); }}
              className={`flex items-center w-full gap-3 px-3 py-3 rounded-lg transition-all border ${
                selectedReportId === report.id ? 'bg-primary-light border-primary/20' : 'hover:bg-surface-accent border-transparent'
              }`}
            >
              <div className={`size-10 flex items-center justify-center rounded-lg flex-shrink-0 ${
                selectedReportId === report.id ? 'bg-primary text-white' : 'bg-surface-accent text-text-secondary'
              }`}>
                <span className="material-symbols-outlined text-[20px]">analytics</span>
              </div>
              <div className="flex flex-col items-start min-w-0 flex-1">
                <div className="flex justify-between w-full items-baseline gap-2">
                  <p className={`text-sm font-bold truncate ${selectedReportId === report.id ? 'text-primary' : 'text-text-main'}`}>
                    {report.symbol} - {report.title}
                  </p>
                  {report.tag && (
                    <span className="text-[8px] uppercase tracking-widest font-black px-1.5 py-0.5 rounded bg-primary/10 text-primary">
                      {report.tag}
                    </span>
                  )}
                </div>
                <p className="text-text-secondary text-[10px] mt-1 uppercase tracking-tight font-medium">{report.date}</p>
              </div>
            </button>
          ))}
        </div>
      </aside>

      <main className="flex-1 flex flex-col overflow-y-auto bg-surface-accent/50 p-6 lg:p-10 relative">
        <div className="max-w-4xl mx-auto w-full bg-white shadow-soft rounded-2xl border border-border-lighter overflow-hidden min-h-full flex flex-col">
          <div className="p-6 md:p-10 border-b border-border-lighter bg-white/80 backdrop-blur sticky top-0 z-10 flex justify-between items-center">
            <div>
              <div className="flex items-center gap-3 mb-1">
                <h2 className="text-2xl font-bold text-text-main">{activeReport.symbol} - Full Analysis</h2>
                <span className="bg-primary-light text-primary text-[10px] font-black uppercase px-2 py-1 rounded-md border border-primary/10">CONFIDENTIAL</span>
              </div>
              <p className="text-text-secondary text-sm flex items-center gap-1">
                Generated by <span className="text-text-main font-bold flex items-center gap-1"><span className="material-symbols-outlined text-[16px]">smart_toy</span> Agent Alpha-7</span> on {activeReport.date.split('•')[0]}
              </p>
            </div>
            <div className="flex gap-2">
              <button onClick={handleAskGemini} disabled={isGenerating} className="flex items-center gap-2 px-4 py-2 bg-primary text-white text-xs font-bold rounded-lg hover:bg-primary-dark shadow-lg shadow-primary/20 transition-all disabled:opacity-50">
                <span className={`material-symbols-outlined text-sm ${isGenerating ? 'animate-spin' : ''}`}>{isGenerating ? 'sync' : 'auto_awesome'}</span>
                {isGenerating ? 'Analyzing...' : 'AI Insights'}
              </button>
              <button className="p-2 text-text-secondary hover:text-primary bg-white border border-border-light rounded-lg">
                <span className="material-symbols-outlined text-sm">download</span>
              </button>
            </div>
          </div>

          <div className="p-6 md:p-10 space-y-8 flex-1">
            {aiAnalysis ? (
              <div className="space-y-8 animate-in fade-in duration-500">
                <div className="bg-primary-light/50 border border-primary/10 rounded-2xl p-6 relative overflow-hidden">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="bg-white p-1.5 rounded-lg text-primary shadow-sm">
                      <span className="material-symbols-outlined text-[20px]">auto_awesome</span>
                    </div>
                    <h3 className="text-lg font-bold text-text-main">AI Executive Summary</h3>
                  </div>
                  <p className="text-text-regular leading-relaxed text-sm md:text-base italic">
                    {aiAnalysis.summary}
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <h3 className="font-bold text-text-main flex items-center gap-2">
                      <span className="w-1 h-5 bg-primary rounded-full"></span> Financial Highlights
                    </h3>
                    <ul className="space-y-2">
                      {aiAnalysis.highlights.map((h: string, i: number) => (
                        <li key={i} className="text-sm text-text-regular flex items-start gap-2">
                          <span className="material-symbols-outlined text-success text-sm mt-0.5">check_circle</span>
                          {h}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className="space-y-4">
                    <h3 className="font-bold text-text-main flex items-center gap-2">
                      <span className="w-1 h-5 bg-purple-500 rounded-full"></span> Technical Outlook
                    </h3>
                    <p className="text-sm text-text-regular bg-surface-accent p-4 rounded-xl border border-border-lighter">
                      {aiAnalysis.technical}
                    </p>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="p-5 rounded-2xl border border-success/10 bg-success/5">
                    <h4 className="font-bold text-success flex items-center gap-2 mb-2">
                      <span className="material-symbols-outlined text-sm">trending_up</span> Bull Case
                    </h4>
                    <p className="text-sm text-text-regular">{aiAnalysis.bullCase}</p>
                  </div>
                  <div className="p-5 rounded-2xl border border-danger/10 bg-danger/5">
                    <h4 className="font-bold text-danger flex items-center gap-2 mb-2">
                      <span className="material-symbols-outlined text-sm">trending_down</span> Bear Case
                    </h4>
                    <p className="text-sm text-text-regular">{aiAnalysis.bearCase}</p>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-20 text-center opacity-40">
                <span className="material-symbols-outlined text-6xl mb-4">article</span>
                <p className="text-lg font-medium">Select AI Insights to generate a deep dive report</p>
                <p className="text-sm">Our multi-agent system uses Gemini 3 Flash to process real-time indicators.</p>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Reports;
